export const NEIGHBORHOOD_SOURCE_REGISTRY = [
  {
    id: 'columbus-development-commission',
    publisher: 'City of Columbus',
    type: 'PRIMARY',
    beats: ['development', 'zoning', 'applications', 'hearing-results'],
    url: 'https://www.columbus.gov/Business-Development/Building-Zoning-Services/Boards-and-Commissions/Development-Commission',
  },
  {
    id: 'columbus-area-commissions',
    publisher: 'City of Columbus',
    type: 'PRIMARY',
    beats: ['area-commission', 'public-meetings', 'resident-context'],
    url: 'https://www.columbus.gov/Government/City-Council/Community-Engagement',
  },
  {
    id: 'columbus-legislation',
    publisher: 'Columbus City Clerk',
    type: 'PRIMARY',
    beats: ['ordinances', 'zoning', 'contracts', 'public-spending'],
    url: 'https://columbus.legistar.com/Legislation.aspx',
  },
  {
    id: 'columbus-permits',
    publisher: 'City of Columbus',
    type: 'PRIMARY',
    beats: ['building-permits', 'zoning-permits', 'inspection-status'],
    url: 'https://portal.columbus.gov/Permits/Welcome.aspx',
  },
  {
    id: 'columbus-gis-zoning-applications',
    publisher: 'City of Columbus GIS',
    type: 'PRIMARY',
    beats: ['parcel-location', 'zoning-applications', 'mapping'],
    url: 'https://gis.columbus.gov/arcgis/rest/services/Applications/Zoning/MapServer',
  },
  {
    id: 'franklin-auditor',
    publisher: 'Franklin County Auditor',
    type: 'PRIMARY',
    beats: ['ownership', 'parcel-history', 'valuation', 'transfers'],
    url: 'https://auditor.franklincountyohio.gov/Auditor/Online-Tools',
  },
  {
    id: 'franklin-recorder',
    publisher: 'Franklin County Recorder',
    type: 'PRIMARY',
    beats: ['deeds', 'mortgages', 'recorded-documents'],
    url: 'https://www.franklincountyohio.gov/Agency-Directory/Recorder/Real-Estate/Public-Records-Search',
  },
  {
    id: 'morpc-data',
    publisher: 'Mid-Ohio Regional Planning Commission',
    type: 'PRIMARY',
    beats: ['transportation', 'housing', 'population', 'regional-plans'],
    url: 'https://www.morpc.org/programs-services/data-mapping-resources/',
  },
  {
    id: 'census-acs',
    publisher: 'U.S. Census Bureau',
    type: 'PRIMARY',
    beats: ['population', 'tenure', 'income', 'housing-stock', 'commuting'],
    url: 'https://data.census.gov/',
  },
];

export const PRIORITY_NEIGHBORHOOD_SLUGS = {
  Bexley: 'bexley',
  Clintonville: 'clintonville',
  Dublin: 'dublin',
  Franklinton: 'franklinton',
  Gahanna: 'gahanna',
  'German Village': 'german-village',
  'Grandview Heights': 'grandview-heights',
  Hilliard: 'hilliard',
  'New Albany': 'new-albany',
  'Short North': 'short-north',
  'Upper Arlington': 'upper-arlington',
  Westerville: 'westerville',
  Worthington: 'worthington',
  'Columbus (city avg)': 'columbus',
};
